#General
num_classes: 4
save_folder: /mnt/disk1/ducntm/ducntm/FmMed/ckpt
embed_ckpt: /mnt/disk1/ducntm/ducntm/FmMed/ckpt/CTVit.39000.pt
root: /mnt/disk1/ducntm/ducntm/DATA/FmMedical
#Model

#Training
lr: 0.0001
epochs: 50