#General
num_classes: 3
save_folder: /home/user01/aiotlab/ducntm/FmMed/ckpt
embed_ckpt: ./ckpt/CTVit.39000.pt
root: /home/user01/aiotlab/thaind/DAC001_CTAC3.75mm_H_1001_PETWB3DAC001/
#Model

#Training
lr: 0.0001
epochs: 50
batch_size: 4